export default [{"description": "Zumwalt Meadow, CA - paper - 8x8", "product": "prod_MV5PNkykHn4t0f", "price": "price_1LtcSNA8Ti7QZNbk7f4sqiyq"},
{"description": "Zumwalt Meadow, CA - paper - 10x8", "product": "prod_MaArbZfaybzl5n", "price": "price_1LtcSOA8Ti7QZNbkyNNxZnJ4"},
{"description": "Zumwalt Meadow, CA - paper - 14x11", "product": "prod_MaArbcOiD78ubG", "price": "price_1LtcSPA8Ti7QZNbknMDgnbu3"},
{"description": "Zumwalt Meadow, CA - paper - 18x12", "product": "prod_MaAr2L0zWP6jl0", "price": "price_1LtcSQA8Ti7QZNbkbIQDPOi0"},
{"description": "Sequoia-Kings Canyon Wilderness, CA - paper - 8x8", "product": "prod_MV5Pqk1KGoLGIG", "price": "price_1LtcSWA8Ti7QZNbkUQyEk6Ha"},
{"description": "Sequoia-Kings Canyon Wilderness, CA - paper - 10x8", "product": "prod_MaArBFSDCVUvaH", "price": "price_1LtcSXA8Ti7QZNbkMVme3Awr"},
{"description": "Sequoia-Kings Canyon Wilderness, CA - paper - 14x11", "product": "prod_MaArok6dlQvloq", "price": "price_1LtcSYA8Ti7QZNbkecjWqxOC"},
{"description": "Sequoia-Kings Canyon Wilderness, CA - paper - 18x12", "product": "prod_MaAru8gSw0DA9j", "price": "price_1LtcSZA8Ti7QZNbkOdk9m2pP"},
{"description": "Capitol Reef, UT - paper - 8x8", "product": "prod_MV5PjCrsRCT1ta", "price": "price_1LtcSeA8Ti7QZNbknHvw5D2J"},
{"description": "Capitol Reef, UT - paper - 8x10", "product": "prod_MV5P6mg8rvqxEl", "price": "price_1LtcSfA8Ti7QZNbk48F1A302"},
{"description": "Capitol Reef, UT - paper - 11x14", "product": "prod_MQD1pMTIbFI48K", "price": "price_1LtcSgA8Ti7QZNbkv9yDzfg9"},
{"description": "Capitol Reef, UT - paper - 12x18", "product": "prod_MV5QoOddkwotPP", "price": "price_1LtcShA8Ti7QZNbkM4POoIO5"},
{"description": "Capitol Reef, UT - paper - 16x20", "product": "prod_MV5QD4v7svEHa6", "price": "price_1LtcSiA8Ti7QZNbkWzuK8Bre"},
{"description": "Dolly Sods, WV - paper - 8x8", "product": "prod_MV5Qt1oac52CQ9", "price": "price_1LtcSnA8Ti7QZNbkbGNW6SV8"},
{"description": "Dolly Sods, WV - paper - 10x8", "product": "prod_MaAsO9joM6ibiq", "price": "price_1LtcSoA8Ti7QZNbkgx3SG7rR"},
{"description": "Dolly Sods, WV - paper - 14x11", "product": "prod_MaAsW7xbALnqTV", "price": "price_1LtcSpA8Ti7QZNbk8IkNCuMe"},
{"description": "Dolly Sods, WV - paper - 18x12", "product": "prod_MaAsQTpx2KOM0p", "price": "price_1LtcSqA8Ti7QZNbkn5Rdda08"},
{"description": "Dolly Sods, WV - paper - 20x16", "product": "prod_MaAshDYnwMpj1b", "price": "price_1LtcSrA8Ti7QZNbkuSNUEJgH"},
{"description": "Big Cottonwood Canyon, UT - paper - 8x8", "product": "prod_MV5Qo5aKTkUfJA", "price": "price_1LtcSxA8Ti7QZNbkXFVD88k9"},
{"description": "Big Cottonwood Canyon, UT - paper - 10x8", "product": "prod_MaAsxnaXuRKRMA", "price": "price_1LtcSyA8Ti7QZNbk4hyIwRrv"},
{"description": "Big Cottonwood Canyon, UT - paper - 14x11", "product": "prod_MaAszAB3P4XcSg", "price": "price_1LtcSzA8Ti7QZNbkd4F5x9Bx"},
{"description": "Big Cottonwood Canyon, UT - paper - 18x12", "product": "prod_MaAs7TUp1enzUa", "price": "price_1LtcT0A8Ti7QZNbkEBAOY9L8"},
{"description": "Spruce Knob, WV - paper - 8x8", "product": "prod_MV5QYQwREp3IYi", "price": "price_1LtcT5A8Ti7QZNbkhZbyKVHt"},
{"description": "Spruce Knob, WV - paper - 10x8", "product": "prod_MaAsy3ZFyS4CkU", "price": "price_1LtcT7A8Ti7QZNbkVRsE4lE7"},
{"description": "Spruce Knob, WV - paper - 14x11", "product": "prod_MaAsKg7wYMezIx", "price": "price_1LtcT8A8Ti7QZNbkiT6QcfI7"},
{"description": "Spruce Knob, WV - paper - 18x12", "product": "prod_MaAsl9L8YpQvL1", "price": "price_1LtcT9A8Ti7QZNbkhp6ba4fa"},
{"description": "Spruce Knob, WV - paper - 20x16", "product": "prod_MaAshec0bep2Pq", "price": "price_1LtcTAA8Ti7QZNbkuAABrMOA"},
{"description": "Badlands, SD - paper - 8x8", "product": "prod_MV5Qpuo3FOIwfx", "price": "price_1LtcUXA8Ti7QZNbkX24dWKWg"},
{"description": "Badlands, SD - paper - 8x10", "product": "prod_MV5QKDxlUzViVu", "price": "price_1LtcUYA8Ti7QZNbkJzA3WRsh"},
{"description": "Badlands, SD - paper - 11x14", "product": "prod_MQD1AkJQB7Cmc3", "price": "price_1LtcUZA8Ti7QZNbkHV8Xtfas"},
{"description": "Badlands, SD - paper - 12x18", "product": "prod_MV5Qrq1AWmcNax", "price": "price_1LtcUaA8Ti7QZNbksFI62WOw"},
{"description": "Badlands, SD - paper - 16x20", "product": "prod_MV5QOKmW9HwYc5", "price": "price_1LtcUbA8Ti7QZNbkkFA4WEvc"},
{"description": "Grand Tetons, WY - paper - 8x8", "product": "prod_MV5QgN5u1z9R7b", "price": "price_1LtcTPA8Ti7QZNbkLmUZst4v"},
{"description": "Grand Tetons, WY - paper - 8x10", "product": "prod_MV5Qu61ASAcKx4", "price": "price_1LtcTQA8Ti7QZNbkZ4yqFGB5"},
{"description": "Grand Tetons, WY - paper - 11x14", "product": "prod_MQD17hhGAazNk1", "price": "price_1LtcTRA8Ti7QZNbkos19dRC1"},
{"description": "Grand Tetons, WY - paper - 12x18", "product": "prod_MV5QdooG0o6ieR", "price": "price_1LtcTTA8Ti7QZNbkCPN8C3oJ"},
{"description": "Grand Tetons, WY - paper - 16x20", "product": "prod_MV5Q2bHWjMur3C", "price": "price_1LtcTUA8Ti7QZNbkMMqU5W1Y"},
{"description": "Shenandoah, VA - paper - 8x8", "product": "prod_MV5QDGSq07pX65", "price": "price_1LtcTZA8Ti7QZNbkhNQHwLcP"},
{"description": "Shenandoah, VA - paper - 10x8", "product": "prod_MaAsvMipDPYbgl", "price": "price_1LtcTaA8Ti7QZNbkjidGn4pw"},
{"description": "Shenandoah, VA - paper - 14x11", "product": "prod_MaAsY3Zu4bbZBL", "price": "price_1LtcTbA8Ti7QZNbkmY63HHpo"},
{"description": "Shenandoah, VA - paper - 18x12", "product": "prod_MaAsXRzyFEItls", "price": "price_1LtcTcA8Ti7QZNbkdBMrt3jA"},
{"description": "Yosemite, CA - paper - 8x8", "product": "prod_MV5QPJS1rSN3cA", "price": "price_1LtcUPA8Ti7QZNbklyLqmEMj"},
{"description": "Yosemite, CA - paper - 10x8", "product": "prod_MaAs7NAew2g2OU", "price": "price_1LtcUQA8Ti7QZNbkWpk0ZOsh"},
{"description": "Yosemite, CA - paper - 14x11", "product": "prod_MaAsLbvdTlUfvD", "price": "price_1LtcURA8Ti7QZNbkWfmI1TKy"},
{"description": "Yosemite, CA - paper - 18x12", "product": "prod_MaAsg8sqPAv47y", "price": "price_1LtcUSA8Ti7QZNbk4C9pTOJR"},
{"description": "Kings Canyon, CA - paper - 8x8", "product": "prod_MV5RqjBlnsMZGS", "price": "price_1LtcTqA8Ti7QZNbkWBUzVyFj"},
{"description": "Kings Canyon, CA - paper - 10x8", "product": "prod_MaAt6V6evYhtox", "price": "price_1LtcTrA8Ti7QZNbkRbyjm19g"},
{"description": "Kings Canyon, CA - paper - 14x11", "product": "prod_MaAtUdv1kS3RQg", "price": "price_1LtcTsA8Ti7QZNbk07G02EX8"},
{"description": "Kings Canyon, CA - paper - 18x12", "product": "prod_MaAtYqZ7CKVKKy", "price": "price_1LtcTtA8Ti7QZNbkejZrIIIB"},
{"description": "Lake Champlain, NY - paper - 8x8", "product": "prod_MV5Rb47hast95F", "price": "price_1LtcTyA8Ti7QZNbk3WNOZ8vO"},
{"description": "Lake Champlain, NY - paper - 10x8", "product": "prod_MaAtMv3ouIhnyo", "price": "price_1LtcTzA8Ti7QZNbkGcH0f2i3"},
{"description": "Lake Champlain, NY - paper - 14x11", "product": "prod_MaAtag7NfZdmwJ", "price": "price_1LtcU0A8Ti7QZNbkIVRPwmbR"},
{"description": "Lake Champlain, NY - paper - 18x12", "product": "prod_MaAtJA8OxII9LX", "price": "price_1LtcU2A8Ti7QZNbkxuUhFo42"},
{"description": "Lake Champlain, NY - paper - 20x16", "product": "prod_MaAtR9eBeJnqwe", "price": "price_1LtcU3A8Ti7QZNbkkH3z2xae"},
{"description": "West Augusta, VA - paper - 8x8", "product": "prod_MV5RTn481LqyJF", "price": "price_1LtcU8A8Ti7QZNbkZ6zbIsym"},
{"description": "West Augusta, VA - paper - 10x8", "product": "prod_MaAtnJRzGkp4o3", "price": "price_1LtcU9A8Ti7QZNbkFGjXQLNU"},
{"description": "West Augusta, VA - paper - 14x11", "product": "prod_MaAtB9iKbv8WJX", "price": "price_1LtcUAA8Ti7QZNbkKKZPsoDO"},
{"description": "West Augusta, VA - paper - 18x12", "product": "prod_MaAtjrZUfi5qJn", "price": "price_1LtcUBA8Ti7QZNbkSUBKKIjn"},
{"description": "Lake Chapin, MI - paper - 8x8", "product": "prod_MV5RR8pfk9hz67", "price": "price_1LtcUGA8Ti7QZNbkNl1j6dVe"},
{"description": "Lake Chapin, MI - paper - 8x10", "product": "prod_MV5RIZlPI0fJaO", "price": "price_1LtcUHA8Ti7QZNbkVZv9OwNZ"},
{"description": "Lake Chapin, MI - paper - 11x14", "product": "prod_MQD1x8zFcs5Mq4", "price": "price_1LtcUIA8Ti7QZNbkrNonja8b"},
{"description": "Lake Chapin, MI - paper - 12x18", "product": "prod_MV5RVwJa25I167", "price": "price_1LtcUJA8Ti7QZNbktUfvdz6G"},
{"description": "Yosemite, CA - paper - 8x8", "product": "prod_MV5QPJS1rSN3cA", "price": "price_1LtcUPA8Ti7QZNbklyLqmEMj"},
{"description": "Yosemite, CA - paper - 10x8", "product": "prod_MaAs7NAew2g2OU", "price": "price_1LtcUQA8Ti7QZNbkWpk0ZOsh"},
{"description": "Yosemite, CA - paper - 14x11", "product": "prod_MaAsLbvdTlUfvD", "price": "price_1LtcURA8Ti7QZNbkWfmI1TKy"},
{"description": "Yosemite, CA - paper - 18x12", "product": "prod_MaAsg8sqPAv47y", "price": "price_1LtcUSA8Ti7QZNbk4C9pTOJR"},
{"description": "Badlands, SD - paper - 8x8", "product": "prod_MV5Qpuo3FOIwfx", "price": "price_1LtcUXA8Ti7QZNbkX24dWKWg"},
{"description": "Badlands, SD - paper - 8x10", "product": "prod_MV5QKDxlUzViVu", "price": "price_1LtcUYA8Ti7QZNbkJzA3WRsh"},
{"description": "Badlands, SD - paper - 11x14", "product": "prod_MQD1AkJQB7Cmc3", "price": "price_1LtcUZA8Ti7QZNbkHV8Xtfas"},
{"description": "Badlands, SD - paper - 12x18", "product": "prod_MV5Qrq1AWmcNax", "price": "price_1LtcUaA8Ti7QZNbksFI62WOw"},
{"description": "Badlands, SD - paper - 16x20", "product": "prod_MV5QOKmW9HwYc5", "price": "price_1LtcUbA8Ti7QZNbkkFA4WEvc"},
{"description": "Savage, MD - paper - 8x8", "product": "prod_MV5RnsIdpGWvxk", "price": "price_1LtcUhA8Ti7QZNbkoAUdfoZR"},
{"description": "Savage, MD - paper - 8x10", "product": "prod_MV5Ry3dt51808n", "price": "price_1LtcUiA8Ti7QZNbk7ZbSJdjh"},
{"description": "Savage, MD - paper - 11x14", "product": "prod_MQD1TLpzvJ4ns2", "price": "price_1LtcUjA8Ti7QZNbknUf3B74M"},
{"description": "Savage, MD - paper - 12x18", "product": "prod_MV5RhoID1wUrcM", "price": "price_1LtcUkA8Ti7QZNbkTGC9hHFz"},
{"description": "Savage, MD - paper - 16x20", "product": "prod_MV5RshVPmB2XEk", "price": "price_1LtcUlA8Ti7QZNbkTOJ3arHg"},
{"description": "Merced River, CA - paper - 8x8", "product": "prod_MV5RGSexhovmwx", "price": "price_1LtcUqA8Ti7QZNbkMTtupXoy"},
{"description": "Merced River, CA - paper - 8x10", "product": "prod_MV5Rd5KHATGyBm", "price": "price_1LtcUrA8Ti7QZNbk8sLQjAy8"},
{"description": "Merced River, CA - paper - 11x14", "product": "prod_MQD13OIqGhGmw4", "price": "price_1LtcUsA8Ti7QZNbk1WPc3AFN"},
{"description": "Merced River, CA - paper - 12x18", "product": "prod_MV5RqQdIds7DWi", "price": "price_1LtcUtA8Ti7QZNbkshKh1ofS"},
{"description": "2019 Lunar Eclipse - paper - 8x8", "product": "prod_MV5StSnwehD1pw", "price": "price_1LtcV1A8Ti7QZNbk1gO3hKWZ"},
{"description": "2019 Lunar Eclipse - paper - 10x8", "product": "prod_MaAttuTuJ3CNMM", "price": "price_1LtcV2A8Ti7QZNbkCf17Zxcn"},
{"description": "2019 Lunar Eclipse - paper - 14x11", "product": "prod_MaAtValvE8wHUH", "price": "price_1LtcV4A8Ti7QZNbk7lSjEIbR"},
{"description": "2019 Lunar Eclipse - paper - 18x12", "product": "prod_MaAueXuZlmaF0v", "price": "price_1LtcV6A8Ti7QZNbkIRROgkjs"},
{"description": "2019 Lunar Eclipse - paper - 20x16", "product": "prod_MaAuGAcrxdPblh", "price": "price_1LtcV8A8Ti7QZNbkqeNVy617"},
{"description": "The Pleiades - paper - 8x8", "product": "prod_MV5SDUChDDGPLH", "price": "price_1LtcVEA8Ti7QZNbkhhWzCOY7"},
{"description": "The Pleiades - paper - 10x8", "product": "prod_MaAum3Y9oHe2cS", "price": "price_1LtcVFA8Ti7QZNbkTyoks44i"},
{"description": "The Pleiades - paper - 14x11", "product": "prod_MaAudcVTeqLJY5", "price": "price_1LtcVGA8Ti7QZNbku2BC1IW9"},
{"description": "The Pleiades - paper - 18x12", "product": "prod_MaAuIAzriT31VP", "price": "price_1LtcVHA8Ti7QZNbkc1ByVHwE"},
{"description": "Bode and Cigar Galaxies - paper - 8x8", "product": "prod_MV5SGWVl9uR5gW", "price": "price_1LtcVLA8Ti7QZNbklcAsQK1q"},
{"description": "Bode and Cigar Galaxies - paper - 10x8", "product": "prod_MaAuzy7K4GBLw3", "price": "price_1LtcVMA8Ti7QZNbktO0RVfcJ"},
{"description": "Bode and Cigar Galaxies - paper - 14x11", "product": "prod_MaAu1fcg8cGtSB", "price": "price_1LtcVNA8Ti7QZNbkvLBtjtnl"},
{"description": "Bode and Cigar Galaxies - paper - 18x12", "product": "prod_MpzbOcGH3u9tJc", "price": "price_1M6JcNA8Ti7QZNbkYXLOyMMW"},
{"description": "Full Moon - paper - 8x8", "product": "prod_MV5SSNj6dxbvkf", "price": "price_1LtcVRA8Ti7QZNbkKAr17OIi"},
{"description": "Full Moon - paper - 10x8", "product": "prod_MaAuv6grgYQvSJ", "price": "price_1LtcVSA8Ti7QZNbk2APHqTAd"},
{"description": "Full Moon - paper - 14x11", "product": "prod_MaAuxv4QntAu8h", "price": "price_1LtcVTA8Ti7QZNbkmHvntZAl"},
{"description": "Orion Nebula - paper - 8x8", "product": "prod_MV5SVdDMxwg9WI", "price": "price_1LtcVYA8Ti7QZNbk2JlM0kcb"},
{"description": "Orion Nebula - paper - 10x8", "product": "prod_MaAuEv2XnJKX5H", "price": "price_1LtcVZA8Ti7QZNbku0LJXR5a"},
{"description": "Orion Nebula - paper - 14x11", "product": "prod_MaAuhTi9IpMLt7", "price": "price_1LtcVaA8Ti7QZNbkVcF81Clw"},
{"description": "Orion Nebula - paper - 18x12", "product": "prod_MaAvHZWqpidZxI", "price": "price_1LtcWZA8Ti7QZNbkEg2YlGBQ"},
{"description": "Eagle Nebula - paper - 8x8", "product": "prod_MV5SN1bYUeGvZF", "price": "price_1LtcVeA8Ti7QZNbkxtAvBNaZ"},
{"description": "Eagle Nebula - paper - 10x8", "product": "prod_MaAuEYlWCzXNwU", "price": "price_1LtcVfA8Ti7QZNbkvd1bBcDi"},
{"description": "Eagle Nebula - paper - 14x11", "product": "prod_MaAuHz1PrmBdQl", "price": "price_1LtcVgA8Ti7QZNbkXoWkzIZr"},
{"description": "Leo Triplet - paper - 8x8", "product": "prod_MV5S47bSl44z6v", "price": "price_1LtcVkA8Ti7QZNbkMno6mSwZ"},
{"description": "Leo Triplet - paper - 10x8", "product": "prod_MaAuzXyWGdegQF", "price": "price_1LtcVlA8Ti7QZNbkpjw8JKZn"},
{"description": "Leo Triplet - paper - 14x11", "product": "prod_Mpzbzyb4RkthJ3", "price": "price_1M6JcTA8Ti7QZNbkyYisHlsn"},
{"description": "Leo Triplet - paper - 18x12", "product": "prod_MpzbuUD2nvYLwA", "price": "price_1M6JcUA8Ti7QZNbkYIgJCoGm"},
{"description": "California Nebula (H-Alpha) - paper - 8x8", "product": "prod_MV5SZLAA03mLlM", "price": "price_1LtcVpA8Ti7QZNbkbAWBFH7X"},
{"description": "California Nebula (H-Alpha) - paper - 10x8", "product": "prod_MaAuJNCSg0XKQn", "price": "price_1LtcVqA8Ti7QZNbkfhlQ4f0v"},
{"description": "California Nebula (H-Alpha) - paper - 14x11", "product": "prod_MaAubWl9nTefis", "price": "price_1LtcVrA8Ti7QZNbkopI2gaIj"},
{"description": "Iris Nebula - paper - 8x8", "product": "prod_Mpzb16SlSu9ChQ", "price": "price_1M6JcXA8Ti7QZNbkawb21lqg"},
{"description": "Iris Nebula - paper - 10x8", "product": "prod_MpzbmgkZ7n1m3t", "price": "price_1M6JcYA8Ti7QZNbkyf1yRqPs"},
{"description": "Orion Nebula (Narrowband) - paper - 8x8", "product": "prod_MV5SuuOGht0oIX", "price": "price_1LtcVxA8Ti7QZNbkWbgmPZ50"},
{"description": "Orion Nebula (Narrowband) - paper - 10x8", "product": "prod_MaAus1Zf4QQ15Q", "price": "price_1LtcVyA8Ti7QZNbkYjNKMzyn"},
{"description": "Orion Nebula (Narrowband) - paper - 14x11", "product": "prod_MaAuBz3Ws2RuEk", "price": "price_1LtcVzA8Ti7QZNbk1QJzTKBq"},
{"description": "Moon Minerals - paper - 8x8", "product": "prod_MV5SUsXCxTUvDN", "price": "price_1LtcW4A8Ti7QZNbkHjy4bdv3"},
{"description": "Moon Minerals - paper - 10x8", "product": "prod_MaAuMfuN6aTLBr", "price": "price_1LtcW5A8Ti7QZNbkIx4KCt7V"},
{"description": "Moon Minerals - paper - 14x11", "product": "prod_MaAuEhlNagE6pV", "price": "price_1LtcW6A8Ti7QZNbk6Vl2h4FY"},
{"description": "Moon Minerals - paper - 18x12", "product": "prod_MaAuJh0kxkJ9d6", "price": "price_1LtcW7A8Ti7QZNbku2z98yzv"},
{"description": "Andromeda Galaxy - paper - 8x8", "product": "prod_MV5TAXlBkkqNMR", "price": "price_1LtcWBA8Ti7QZNbkvNZr11bv"},
{"description": "Andromeda Galaxy - paper - 10x8", "product": "prod_MaAus5TR9wi2HH", "price": "price_1LtcWCA8Ti7QZNbkvBu17eC3"},
{"description": "Andromeda Galaxy - paper - 14x11", "product": "prod_MaAuCNrdoItEqX", "price": "price_1LtcWDA8Ti7QZNbk6b8z3GgW"},
{"description": "Andromeda Galaxy - paper - 18x12", "product": "prod_Mpzb9meqZStu48", "price": "price_1M6JcdA8Ti7QZNbkg4sNHjVH"},
{"description": "Eastern Veil Nebula - paper - 8x8", "product": "prod_MV5TdXtXXKAr7J", "price": "price_1LtcWHA8Ti7QZNbkpnUX31uE"},
{"description": "Eastern Veil Nebula - paper - 10x8", "product": "prod_MaAuC0EfNSMh0H", "price": "price_1LtcWIA8Ti7QZNbkasWaitfz"},
{"description": "Eastern Veil Nebula - paper - 14x11", "product": "prod_MaAuO4gihXKmRW", "price": "price_1LtcWJA8Ti7QZNbkCVTdHxrH"},
{"description": "Dumbbell Nebula - paper - 8x8", "product": "prod_MpzbXN1dhGeE0E", "price": "price_1M6JcfA8Ti7QZNbkKel4oLqt"},
{"description": "Dumbbell Nebula - paper - 10x8", "product": "prod_MpzbC5RdBRPk80", "price": "price_1M6JcgA8Ti7QZNbkBxeFsAls"},
{"description": "Crescent Nebula - paper - 8x8", "product": "prod_MV5TS84xndCa4f", "price": "price_1LtcWOA8Ti7QZNbkZlKyn5tG"},
{"description": "Crescent Nebula - paper - 10x8", "product": "prod_MaAvlBetlELC2z", "price": "price_1LtcWPA8Ti7QZNbkOeQbbilV"},
{"description": "Crescent Nebula - paper - 14x11", "product": "prod_MaAvrIB8wB61ZL", "price": "price_1LtcWQA8Ti7QZNbk1LNb7Ez0"},
{"description": "Orion Nebula (Trapezium) - paper - 8x8", "product": "prod_MV5TcLefhhDa0K", "price": "price_1LtcWWA8Ti7QZNbk0bR4wR8m"},
{"description": "Orion Nebula (Trapezium) - paper - 10x8", "product": "prod_MaAvyi6CuGikPT", "price": "price_1LtcWXA8Ti7QZNbkXuoTZKHW"},
{"description": "Orion Nebula (Trapezium) - paper - 14x11", "product": "prod_MaAvJM2D3R6Mb8", "price": "price_1LtcWYA8Ti7QZNbkM59hs320"},
{"description": "Orion Nebula (Trapezium) - paper - 18x12", "product": "prod_MaAvHZWqpidZxI", "price": "price_1LtcWZA8Ti7QZNbkEg2YlGBQ"},
{"description": "Lagoon Nebula - paper - 8x8", "product": "prod_MV5Tf1RLMPec1B", "price": "price_1LtcWbA8Ti7QZNbkN1a3Bn8M"},
{"description": "Lagoon Nebula - paper - 10x8", "product": "prod_MaAvt7QSS9Cdoq", "price": "price_1LtcWcA8Ti7QZNbkzzevCDDr"},
{"description": "Western Veil Nebula - paper - 8x8", "product": "prod_MV5TpCM7ajFYH0", "price": "price_1LtcYmA8Ti7QZNbkUteHszQr"},
{"description": "Western Veil Nebula - paper - 10x8", "product": "prod_MaAv8oNBQPvvZS", "price": "price_1LtcYnA8Ti7QZNbkkpsDpL9S"},
{"description": "Bear - paper - 8x8", "product": "prod_MV5TZ0OzKXckYx", "price": "price_1LtcWnA8Ti7QZNbkrwkgc8Co"},
{"description": "Bear - paper - 10x8", "product": "prod_MaAv5ch8HG51em", "price": "price_1LtcWoA8Ti7QZNbkQqFImrdg"},
{"description": "Bear - paper - 14x11", "product": "prod_MaAvseP5tgjisu", "price": "price_1LtcWqA8Ti7QZNbkkRBPOqPP"},
{"description": "Bear - paper - 18x12", "product": "prod_MaAvxNZ26BJBUG", "price": "price_1LtcWsA8Ti7QZNbkfAO6MeiB"},
{"description": "Bear - paper - 20x16", "product": "prod_MaAvfZUPfjCzGA", "price": "price_1LtcWuA8Ti7QZNbkRzgt6pJB"},
{"description": "Flame - paper - 8x8", "product": "prod_MV5To6eddGLi1V", "price": "price_1LtcWzA8Ti7QZNbkjZh9zSrN"},
{"description": "Flame - paper - 10x8", "product": "prod_MaAvcd8wC3aVco", "price": "price_1LtcX0A8Ti7QZNbkEUCMbaRa"},
{"description": "Sea Shell - paper - 8x8", "product": "prod_MV5TsheMIAUoGf", "price": "price_1LtcX7A8Ti7QZNbke16yTL4k"},
{"description": "Sea Shell - paper - 10x8", "product": "prod_MaAva4w5jRb9xd", "price": "price_1LtcX8A8Ti7QZNbkjZKzfRv3"},
{"description": "Sea Shell - paper - 14x11", "product": "prod_MaAvK5DBR1DBFH", "price": "price_1LtcXBA8Ti7QZNbkOHvpon9F"},
{"description": "Sea Shell - paper - 18x12", "product": "prod_MaAvZiU7fCXh7p", "price": "price_1LtcXDA8Ti7QZNbk2tUFDpvK"},
{"description": "Sea Shell - paper - 20x16", "product": "prod_MaAvNVa2sFSEkJ", "price": "price_1LtcXFA8Ti7QZNbk7lt2fKjY"},
{"description": "Snowflake - paper - 8x8", "product": "prod_MV5TPPeqqGUi5s", "price": "price_1LtcXNA8Ti7QZNbkqlrxQN3q"},
{"description": "Snowflake - paper - 10x8", "product": "prod_MaAvdZzsuMm50h", "price": "price_1LtcXOA8Ti7QZNbk17JjKvV0"},
{"description": "Snowflake - paper - 14x11", "product": "prod_MaAvSH5H7k5NDS", "price": "price_1LtcXQA8Ti7QZNbkFryQTu8H"},
{"description": "Snowflake - paper - 18x12", "product": "prod_MaAvIG70CidurD", "price": "price_1LtcXSA8Ti7QZNbkIZoGKp29"},
{"description": "Snowflake - paper - 20x16", "product": "prod_MaAvjRhTGNQlqM", "price": "price_1LtcXVA8Ti7QZNbkdV6qbS82"},
{"description": "Flower - paper - 8x8", "product": "prod_MV5ULJMmBQ34x9", "price": "price_1LtcXeA8Ti7QZNbkzn0fQwDp"},
{"description": "Flower - paper - 10x8", "product": "prod_MaAwY3XNgWljfg", "price": "price_1LtcXfA8Ti7QZNbkexJ3ge5i"},
{"description": "Flower - paper - 14x11", "product": "prod_MaAwKN8LbkE458", "price": "price_1LtcXhA8Ti7QZNbk2vPYXlu4"},
{"description": "Flower - paper - 18x12", "product": "prod_MaAwNp3GhuPilF", "price": "price_1LtcXjA8Ti7QZNbkMXb0NlLt"},
{"description": "Flower - paper - 20x16", "product": "prod_MaAw7grIbJUspq", "price": "price_1LtcXlA8Ti7QZNbkMn5moAs5"},
{"description": "Sea Horse - paper - 8x8", "product": "prod_MV5UJkb5aXpuWZ", "price": "price_1LtcXpA8Ti7QZNbklPE5C3Wc"},
{"description": "Sea Horse - paper - 10x8", "product": "prod_MaAwedHKecglQd", "price": "price_1LtcXqA8Ti7QZNbkMMCInvdT"},
{"description": "Jewel - paper - 8x8", "product": "prod_MV5UZfHXLWoust", "price": "price_1LtcXvA8Ti7QZNbkgI8GF1C1"},
{"description": "Jewel - paper - 10x8", "product": "prod_MaAws2JvF8tD82", "price": "price_1LtcXwA8Ti7QZNbkIPW4mZZM"},
{"description": "Smoke - paper - 8x8", "product": "prod_MV5UE37VBrFdCL", "price": "price_1LtcY1A8Ti7QZNbkJZmAT2qj"},
{"description": "Smoke - paper - 10x8", "product": "prod_MaAwSQ1YVpoGp4", "price": "price_1LtcY2A8Ti7QZNbkGvdB9ZZR"},
{"description": "Smoke - paper - 14x11", "product": "prod_MaAwQYDamxZOTo", "price": "price_1LtcY3A8Ti7QZNbkOy3Lb1yW"},
{"description": "Orbit - paper - 8x8", "product": "prod_MV5UBx19M40pDB", "price": "price_1LtcY6A8Ti7QZNbkllOQHDwm"},
{"description": "Orbit - paper - 10x8", "product": "prod_MaAwO54PazlvGk", "price": "price_1LtcY7A8Ti7QZNbkWyfE7aBL"},
{"description": "Orbit - paper - 14x11", "product": "prod_MvA54E8YXzeOpr", "price": "price_1MBJlnA8Ti7QZNbkYZFgXLTM"},
{"description": "Orbit - paper - 18x12", "product": "prod_MvA6EyMspSkMFm", "price": "price_1MBJloA8Ti7QZNbk8hZgAt1e"},
{"description": "Tricorn - paper - 8x8", "product": "prod_MV5U6aexPYsfeg", "price": "price_1LtcYEA8Ti7QZNbkMkiymJYx"},
{"description": "Tricorn - paper - 10x8", "product": "prod_MaAwKEPLr0wzXU", "price": "price_1LtcYGA8Ti7QZNbkzPe5l9J0"},
{"description": "Tricorn - paper - 14x11", "product": "prod_MaAw58jM40GYeA", "price": "price_1LtcYIA8Ti7QZNbkerBvJ8yl"},
{"description": "Tricorn - paper - 18x12", "product": "prod_MaAwnxGJX5KfLw", "price": "price_1LtcYKA8Ti7QZNbkNpB41dOc"},
{"description": "Tricorn - paper - 20x16", "product": "prod_MaAwhrZ9fWkxGa", "price": "price_1LtcYMA8Ti7QZNbkVVnlVwfJ"},
{"description": "Chaos - paper - 8x8", "product": "prod_MV5UDhk36CM6pb", "price": "price_1LtcYSA8Ti7QZNbkjSnaKKep"},
{"description": "Chaos - paper - 8x10", "product": "prod_MV5UaG6dTQ2mvX", "price": "price_1LtcYTA8Ti7QZNbkHxopjv6s"},
{"description": "Chaos - paper - 11x14", "product": "prod_MQD2KjpFvX6Djf", "price": "price_1LtcYUA8Ti7QZNbkvy2akxny"},
{"description": "Feather - paper - 8x8", "product": "prod_MV5UEGy11JIGQ5", "price": "price_1LtcYcA8Ti7QZNbkAA7VxZiQ"},
{"description": "Feather - paper - 10x8", "product": "prod_MaAwas18VEXSv4", "price": "price_1LtcYdA8Ti7QZNbkXrfbO9jX"},
{"description": "Feather - paper - 14x11", "product": "prod_MaAwgPOt1fyZpv", "price": "price_1LtcYfA8Ti7QZNbkH9oCpNKH"},
{"description": "Feather - paper - 18x12", "product": "prod_MaAwdeeVXnH77E", "price": "price_1LtcYhA8Ti7QZNbkL7pb4KDm"},
{"description": "Feather - paper - 20x16", "product": "prod_MaAxFwm99A48kO", "price": "price_1LtcYjA8Ti7QZNbkik5tKr9Q"},
{"description": "Nebula - paper - 8x8", "product": "prod_MV5TpCM7ajFYH0", "price": "price_1LtcYmA8Ti7QZNbkUteHszQr"},
{"description": "Nebula - paper - 10x8", "product": "prod_MaAv8oNBQPvvZS", "price": "price_1LtcYnA8Ti7QZNbkkpsDpL9S"},
{"description": "Clover - paper - 8x8", "product": "prod_MV5UHMRITxHo8Q", "price": "price_1LtcYtA8Ti7QZNbk6zbKXyhc"},
{"description": "Clover - paper - 10x8", "product": "prod_MaAx4oCsCooPLB", "price": "price_1LtcYuA8Ti7QZNbkMoFl6sW5"},
{"description": "Clover - paper - 14x11", "product": "prod_MaAx14Sg8iXXvJ", "price": "price_1LtcYvA8Ti7QZNbkOfCJMXhr"},
{"description": "Gateway - paper - 8x8", "product": "prod_MV5VMXQ1zW3PIT", "price": "price_1LtcYzA8Ti7QZNbkNztGau6w"},
{"description": "Gateway - paper - 10x8", "product": "prod_MaAxbYbxN1UfmE", "price": "price_1LtcZ0A8Ti7QZNbkMQauDzp9"},
{"description": "Throne - paper - 8x8", "product": "prod_MV5VC8NUTqqYGA", "price": "price_1LtcZ8A8Ti7QZNbkQvDTohE7"},
{"description": "Throne - paper - 10x8", "product": "prod_MaAxq5fi8bN7EJ", "price": "price_1LtcZ9A8Ti7QZNbk2D5MPCJQ"},
{"description": "Throne - paper - 14x11", "product": "prod_MaAxrHNapRtCeh", "price": "price_1LtcZBA8Ti7QZNbkBh3llM0k"},
{"description": "Rose - paper - 8x8", "product": "prod_MV5VgCrwR8Fi2G", "price": "price_1LtcZJA8Ti7QZNbkZPJXOkXc"},
{"description": "Rose - paper - 10x8", "product": "prod_MaAxfjLpepNHTv", "price": "price_1LtcZKA8Ti7QZNbkSFPIiASD"},
{"description": "Rose - paper - 14x11", "product": "prod_MaAx1zDkGjCSoo", "price": "price_1LtcZMA8Ti7QZNbkdDqxS8Yl"},
{"description": "Rose - paper - 18x12", "product": "prod_MaAx5mUZErSoMU", "price": "price_1LtcZOA8Ti7QZNbkP7gjELMs"},
{"description": "Rose - paper - 20x16", "product": "prod_MaAxrxrwZ2O5Dq", "price": "price_1LtcZRA8Ti7QZNbkQBj9I4M6"},
{"description": "Butterfly - paper - 8x8", "product": "prod_MV5VTlhEqOpDnV", "price": "price_1LtcZXA8Ti7QZNbkdSBCKsXz"},
{"description": "Butterfly - paper - 10x8", "product": "prod_MaAxphdcwIGxsh", "price": "price_1LtcZYA8Ti7QZNbkPtYVvXJg"},
{"description": "Butterfly - paper - 14x11", "product": "prod_MaAx0BAkm8ZUKz", "price": "price_1LtcZZA8Ti7QZNbkSZWXgSve"},
{"description": "Butterfly - paper - 18x12", "product": "prod_MaAxRyqEUuhD8U", "price": "price_1LtcZaA8Ti7QZNbkouHWHRNl"}];